name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Log in to Docker on EC2
            echo "$DOCKER_HUB_PASSWORD" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin

            # Pull the latest image from Docker Hub
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest

            # Stop and remove any old container
            sudo docker stop fastapi-app || true
            sudo docker rm fastapi-app || true

            # Run the new container
            sudo docker run -d --name fastapi-app -p 8000:8000 --restart=always ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest

            # Restart Nginx to apply changes
            sudo systemctl restart nginx
